// browser/src/App.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Buffer } from 'buffer'
	import * as AutoR1 from '@autor1/lib';
	import * as Neutralino from '@neutralinojs/lib';
	import {
	handleViewConfig,
} from '../../lib/src/viewTemplates';
	import {
		downloadFile,
		init,
		alert,
		openProjectDialog,
	} from '../../native/frontend/src/windows/main/neutrino';
	import { config } from '../../lib/src/defaultViews';

	const GROUP_NAME = 'AutoR1';
	const SUFFIX = '_AUTO';

	const newAutoPath = (path: string) => path.substring(0, path.lastIndexOf('.')) + SUFFIX + '.dbpr';

	const versionString = (window as any).NL_APPVERSION || '-2';
	const commitString = (window as any).NL_COMMIT
		? (window as any as { NL_COMMIT: string }).NL_COMMIT.substring(
				(window as any as { NL_COMMIT: string }).NL_COMMIT.length - 5
			) + (window as any).NL_CCOMMIT?.substring((window as any).NL_CCOMMIT.length - 5)
		: '-1';

	const DEFAULT_OPTIONS: AutoR1.ProjectOptions = {
		main: true,
		meter: true,
		eq: true,
		arraySightControls: true
	};

	let defaultTemplateFile: AutoR1.AutoR1TemplateFile | undefined = $state();
	let templateFile: AutoR1.AutoR1TemplateFile | undefined = $state();

	let projectFile: AutoR1.AutoR1ProjectFile | undefined = $state();
	let projectFileBuffer: Buffer | undefined = $state();
	let projectOptions: AutoR1.ProjectOptions = $state({ ...DEFAULT_OPTIONS });
	let fileName: string = $state('');
	let customTemplateFileName = $state('');
	let sourceGroupsStatus: SourceGroupStatus[] | undefined = $state();
	let isVisible = $state(false);

	interface SourceGroupStatus {
		fallback: boolean;
		mute: boolean;
		ds: boolean;
		eq: boolean;
	}

	onMount(async () => {
		init();

		const arrayBuffer = await Neutralino.filesystem.readBinaryFile('../lib/Projects/templates.r2t');
		const buffer = new Uint8Array(arrayBuffer);
		defaultTemplateFile = await AutoR1.AutoR1TemplateFile.build(Buffer.from(buffer));
		templateFile = defaultTemplateFile;
	});

	function base64ToArrayBuffer(base64: string) {
		var binaryString = atob(base64);
		var bytes = new Uint8Array(binaryString.length);
		for (var i = 0; i < binaryString.length; i++) {
			bytes[i] = binaryString.charCodeAt(i);
		}
		return bytes.buffer;
	}

	function toggleVisibility() {
		isVisible = !isVisible;
	}

	const newCleanPath = (path: string) =>
		path.substring(0, path.lastIndexOf('.')) + 'CLEAN' + '.dbpr';

	function resetStatus() {
		if (projectFile) {
			sourceGroupsStatus = projectFile.sourceGroups.map((sg) => ({
				fallback: sg.fallback,
				mute: sg.mute,
				ds: sg.dsData,
				eq: sg.eq
			}));
		}
		projectOptions = { ...DEFAULT_OPTIONS };
		clearCustomTemplateFile();
	}

	async function cleanFile() {
		if (projectFileBuffer) {
			const projectFile = await AutoR1.AutoR1ProjectFile.build(projectFileBuffer);
			const id = projectFile.getGroupIdFromName(GROUP_NAME);
			projectFile.clean(id);

			const arraybuff = projectFile.db.export();

			downloadFile(arraybuff, newCleanPath(fileName!));

			alert('Cleaned project has been downloaded.');
		}
	}

	function clearFile() {
		projectFile = undefined;
		fileName = '';
		sourceGroupsStatus = undefined;
		projectFileBuffer = undefined;

		clearCustomTemplateFile();
	}

	const processFile = async (
		fileBuffer: Buffer,
		status: SourceGroupStatus[],
		options: AutoR1.ProjectOptions
	) => {
		let projectFile: AutoR1.AutoR1ProjectFile;
		projectFile = await AutoR1.AutoR1ProjectFile.build(fileBuffer!);

		if (projectFile.additions) {
			const id = projectFile.getGroupIdFromName(GROUP_NAME);
			projectFile.clean(id);
		}

		const parentId = projectFile.createGroup({ Name: GROUP_NAME });
		projectFile.createSubLRCGroups(parentId);
		projectFile.getSrcGrpInfo();

		status.forEach((row, i) => {
			projectFile.sourceGroups[i].fallback = row.fallback;
			projectFile.sourceGroups[i].mute = row.mute;
			projectFile.sourceGroups[i].dsData = row.ds;
			projectFile.sourceGroups[i].eq = row.eq;
		});

		

		config.forEach((view) => handleViewConfig(view, projectFile, templateFile!));

		const arraybuff = projectFile.db.export();

		downloadFile(arraybuff, newAutoPath(fileName));

		return projectFile;
	};

	function handleDrop(event: Event) {
		const [file] = (event.target as HTMLInputElement).files!;
		loadProjectFile(file).then((loadedfile) => projectFile = loadedfile)
	}

	function handleTemplateFileDrop(event: Event) {
		const [file] = (event.target as HTMLInputElement).files!;
		loadTemplateFile(file);
	}

	const toggleAllStatus = (prop: 'fallback' | 'mute' | 'ds' | 'eq') => {
		if (sourceGroupsStatus) {
			sourceGroupsStatus = sourceGroupsStatus.map((row) => ({
				...row,
				[prop]: !row[prop]
			}));
		}
	};

	const toggleRowStatus = (index: number) => {
		if (sourceGroupsStatus) {
			const row = sourceGroupsStatus[index];
			sourceGroupsStatus[index] = {
				fallback: !row.fallback,
				mute: !row.mute,
				ds: !row.ds,
				eq: !row.eq
			};
		}
	};

	function statusHasChanged() {
		return (
			sourceGroupsStatus?.some((row) => !row.fallback || !row.mute || !row.ds || !row.eq) ||
			!projectOptions.main ||
			!projectOptions.meter ||
			!projectOptions.eq ||
			!projectOptions.arraySightControls ||
			customTemplateFileName
		);
	}

	const loadDbpr = (droppedFile: File) =>
		new Promise<Buffer>((res) => {
			const reader = new FileReader();
			reader.onload = async (event) => {
				const fileContent = event.target!.result! as ArrayBuffer;
				const buffer = Buffer.from(new Uint8Array(fileContent));

				res(buffer);
			};
			reader.readAsArrayBuffer(droppedFile);
		});

	const loadProjectFile = async (droppedFile: File) => {
		const buffer = await loadDbpr(droppedFile);
		let newProjectFile: AutoR1.AutoR1ProjectFile;
		newProjectFile = await AutoR1.AutoR1ProjectFile.build(buffer);
		if (newProjectFile.additions) {
			const id = newProjectFile.getGroupIdFromName(GROUP_NAME);
			if (!id) {
				throw new Error('Project has AutoR1 additions but the main group can not be found.');
			}
			newProjectFile.clean(id);
		}
		const parentId = newProjectFile.createGroup({
			Name: GROUP_NAME
		});
		newProjectFile.createSubLRCGroups(parentId);
		newProjectFile.getSrcGrpInfo();

		projectFileBuffer = buffer;
		fileName = droppedFile!.name;
		sourceGroupsStatus = newProjectFile.sourceGroups.map((sg) => ({
			fallback: sg.fallback,
			mute: sg.mute,
			ds: sg.dsData,
			eq: sg.eq
		}));

		return newProjectFile;
	};

	const loadTemplateFile = async (droppedFile: File) => {
		const buffer = await loadDbpr(droppedFile);
		let newTemplateFile = await AutoR1.AutoR1TemplateFile.build(buffer);
		return newTemplateFile;
	};

	const handleTemplateFileClick = async () => {
		const file = await openProjectDialog();

		try {
			templateFile = await loadTemplateFile(file);
			customTemplateFileName = file.name.split('/')[file.name.split('/').length - 1];
		} catch (e) {
			console.log(e);
			alert('Failed to load template file.');
		}
	};

	const clearCustomTemplateFile = () => {
		templateFile = defaultTemplateFile;
		customTemplateFileName = '';
	};

	const handleTemplateFileDownload = () => {
		const arraybuff = templateFile!.db.export();
		downloadFile(arraybuff, './templates.r2t')
	};

	const handleInputClick = async () => {
		const file = await openProjectDialog();
		try {
			projectFile = await loadProjectFile(file);
		} catch (e: any) {
			alert(`AutoR1 has encountered the following error while processing ${file.name}:\n${e}`);

			clearFile();
			return;
		}
	};
</script>

<main
	class="flex h-full select-none flex-col justify-center bg-white font-mono text-zinc-800 dark:bg-zinc-800 dark:text-zinc-50"
>
	<div class="mx-auto flex max-w-lg flex-col items-center">
		<div class="my-5 flex w-max flex-col items-center">
			<h1 class="text-4xl font-bold">AutoR1 2.0 Beta</h1>
		</div>

		{#if !projectFile}
			<div class="flex w-max flex-col items-center">
				<div class="relative">
					<input
						class="absolute inset-0 z-50 m-0 h-full w-full cursor-pointer p-1 opacity-0 outline-none"
						type="file"
						id="fileInput"
						accept=".dbpr"
						onchange={handleDrop}
					/>
					<div
						class="flex h-48 cursor-pointer items-center justify-center border-2 border-solid border-slate-700 hover:border-slate-400"
					>
						<div>Click to load a .DBPR file or drag and drop.</div>
					</div>
				</div>
			</div>
		{/if}

		{#if projectFile}
			<div class="flex w-full flex-col items-center px-3">
				<div class="my-5 flex flex-col items-center">
					<h1 class="text-center text-4xl font-bold">
						{fileName.split('/')[fileName.split('/').length - 1]}
					</h1>
				</div>
				<div>
					<p>Initial setup performed: ✅</p>
					{#if projectFile.additions}
						<p>Already contains AutoR1 additions: <span>✅</span></p>
					{/if}
				</div>
				<div class="w-full">
					<div class="text-med my-2 flex h-8 justify-around gap-x-2">
						<button
							class="flex-grow-1 basis-1/4 rounded-md bg-lime-500"
							style="flex-grow: 1;"
							onclick={() => processFile(file!, sourceGroupsStatus!, projectOptions)}
						>
							<span style="margin-right: 0.4vw;">▶️</span><span>Run</span>
						</button>
						{#if projectFile.additions}
							<button
								class="basis-1/4 rounded-md bg-slate-200 dark:bg-slate-500"
								style="flex-grow: 1;"
								onclick={cleanFile}
							>
								<span style="margin-right: 0.4vw;">🧹</span><span>Clean</span>
							</button>
						{/if}
						<button
							class="basis-1/4 rounded-md bg-slate-200 dark:bg-slate-500"
							style="flex-grow: 1;"
							onclick={clearFile}
						>
							<span style="margin-right: 0.4vw;">⏮️</span><span>Clear</span>
						</button>
						<button
							class="basis-1/4 rounded-md bg-slate-200 dark:bg-slate-500"
							style="flex-grow: 1;"
							onclick={toggleVisibility}
						>
							<span style="margin-right: 0.4vw;">{isVisible ? '⤴️' : '⤵️'}</span>
							<span>{isVisible ? 'Hide' : 'Show'}</span>
						</button>
						{#if isVisible && statusHasChanged()}
							<button
								class="basis-1/4 rounded-md bg-slate-200 dark:bg-slate-500"
								style="flex-grow: 1;"
								onclick={resetStatus}
							>
								<span style="margin-right: 0.4vw;">⏪</span><span>Reset</span>
							</button>
						{/if}
					</div>
					{#if isVisible}
						<div class="flex flex-col items-center">
							<div class="w-full">
								<div class="flex justify-end">
									<div class="w-fit basis-2/3">Main page</div>
									<input class="basis-1/3" type="checkbox" bind:checked={projectOptions.main} />
								</div>
								<div class="flex justify-end">
									<div class="w-fit basis-2/3">Meter page</div>
									<input class="basis-1/3" type="checkbox" bind:checked={projectOptions.meter} />
								</div>
								<div class="flex justify-end">
									<div class="w-fit basis-2/3">EQ page</div>
									<input class="basis-1/3" type="checkbox" bind:checked={projectOptions.eq} />
								</div>
								<div class="flex justify-end">
									<div class="w-fit basis-2/3">ArraySight controls</div>
									<input
										class="basis-1/3"
										type="checkbox"
										bind:checked={projectOptions.arraySightControls}
									/>
								</div>
								<div class="flex justify-between gap-1" title="Load a custom .r2t template file.">
									<div class="w-fit basis-1/2">Custom templates:</div>
									{#if !customTemplateFileName}
										<input type="file" id="templateInput" class="hidden" accept=".r2t" />
										<button
											class="w-full basis-1/4 cursor-pointer rounded-md bg-slate-200 dark:bg-slate-500 text-center"
											onchange={handleTemplateFileDrop}
											onclick={handleTemplateFileClick}
										>
											Load
										</button>
										<button
											class="w-full basis-1/4 cursor-pointer rounded-md bg-slate-200 dark:bg-slate-500 text-center"
											onclick={handleTemplateFileDownload}
										>
											Get
										</button>
									{:else}
										<button
											class="w-full basis-1/2 cursor-pointer rounded-md bg-slate-200 text-center"
											onclick={clearCustomTemplateFile}
										>
											<span class="text-xs">{customTemplateFileName}</span>
											<span>❌</span>
										</button>
									{/if}
								</div>
							</div>
							<table id="sourceGroupTable" class="w-full text-center">
								<thead>
									<tr>
										<th>Source Group</th>
										<th class="cursor-pointer" onclick={() => toggleAllStatus('fallback')}
											>Fallback</th
										>
										<th class="cursor-pointer" onclick={() => toggleAllStatus('mute')}>Mute</th>
										<th class="cursor-pointer" onclick={() => toggleAllStatus('ds')}>DS Data</th>
									</tr>
								</thead>
								<tbody>
									{#each sourceGroupsStatus! as row, index}
										<tr>
											<td class="cursor-pointer" onclick={() => toggleRowStatus(index)}>
												{projectFile?.sourceGroups?.[index]?.Name}
											</td>
											<td><input type="checkbox" bind:checked={row.fallback} /></td>
											<td><input type="checkbox" bind:checked={row.mute} /></td>
											<td><input type="checkbox" bind:checked={row.ds} /></td>
										</tr>
									{/each}
								</tbody>
							</table>
						</div>
					{/if}
				</div>
			</div>
		{/if}
		{#if !(window as any).NL_APPVERSION}
			<div class="my-4 text-center text-sm">
				All files are processed on-device and are not uploaded or stored remotely. An internet
				connection is not required once the page has loaded.
			</div>
		{/if}
		<div class="mb-3 mt-3 flex flex-col items-center">
			<div class="mb-3 p-2 hover:rounded-md hover:bg-slate-400">
				<a class="text-sm" href="https://discord.gg/xWMcNGc4FF">
					<img
						class="mr-2 inline"
						width="25rem"
						src="https://cdn.prod.website-files.com/6257adef93867e50d84d30e2/653714c174fc6c8bbea73caf_636e0a69f118df70ad7828d4_icon_clyde_blurple_RGB.svg"
						alt="Discord logo"
					/>Join the Discord</a
				>
			</div>
			<div style="height:3em;width:10em;">
				<a href=" https://www.buymeacoffee.com/Lachlanc"
					><img
						alt="Buy my a coffee donation button"
						src="https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=&slug=Lachlanc&button_colour=FFDD00&font_colour=000000&font_family=Inter&outline_colour=000000&coffee_colour=ffffff"
					/></a
				>
			</div>
		</div>
		<div style="font-size: 0.5em;">
			<span>Created by Lachlan Cresswell.</span>
			<span>v{versionString}-{commitString}</span>-<span> </span>
		</div>
	</div>
</main>

// src/App.tsx
import React, { useEffect, useState } from 'react';
import { Buffer } from 'buffer';
import * as AutoR1 from './autor1';
import './App.css';

const TEMPLATES = process.env.PUBLIC_URL + '/templates.r2t';
const GROUP_NAME = 'AutoR1'
const SUFFIX = '_AUTO';

let templates: AutoR1.AutoR1TemplateFile;

/**
 * Creates a new path for the processed R1 project file
 * @param path
 * @returns New path
 */
const newAutoPath = (path: string) => path.substring(0, path.lastIndexOf('.')) + SUFFIX + '.dbpr';

/**
 * Downloads the processed file
 * @param projectFile
 * @param filename
 * @returns Download link
 */
const downloadFile = (projectFile: AutoR1.AutoR1ProjectFile, filename: string) => {
  const arraybuff = projectFile.db.export();

  var blob = new Blob([arraybuff]);
  const link = window.URL.createObjectURL(blob);

  var a = document.createElement("a");
  document.body.appendChild(a);
  a.href = link;
  a.download = filename;
  a.click();
  a.remove();

  return link
}

/**
 * Applies AutoR1 additions to a project file
 * @param fileBuffer
 * @param status
 * @returns Processed project file
 */
const processFile = async (fileBuffer: Buffer, status: SourceGroupStatus[], options: AutoR1.ProjectOptions) => {
  let projectFile: AutoR1.AutoR1ProjectFile;
  projectFile = await AutoR1.AutoR1ProjectFile.build(fileBuffer!);

  if (projectFile.additions) {
    const id = projectFile.getGroupIdFromName(GROUP_NAME);
    projectFile.clean(id);
  }

  const parentId = projectFile.createGroup({ Name: GROUP_NAME });
  projectFile.createSubLRCGroups(parentId);
  projectFile.getSrcGrpInfo();

  status.forEach((row, i) => {
    projectFile.sourceGroups[i].fallback = row.fallback;
    projectFile.sourceGroups[i].mute = row.mute;
    projectFile.sourceGroups[i].dsData = row.ds;
  });

  projectFile.createAll(templates, parentId!, options);

  return projectFile;
}

interface SourceGroupStatus {
  fallback: boolean;
  mute: boolean;
  ds: boolean;
}


const DEFAULT_OPTIONS: AutoR1.ProjectOptions = {
  main: true,
  meter: true,
  eq: true,
  arraySightControls: true
}

function App() {
  const [projectFile, setProjectFile] = useState<AutoR1.AutoR1ProjectFile | null>(null);
  const [isDragOver, setIsDragOver] = useState<boolean>(false);
  const [fileName, setFileName] = useState<string | undefined>(undefined);
  const [sourceGroupsStatus, setSourceGroupsStatus] = useState<SourceGroupStatus[] | undefined>(undefined);
  const [projectOptions, setProjectOptions] = useState<AutoR1.ProjectOptions>(DEFAULT_OPTIONS);
  const [fileBuffer, setFileBuffer] = useState<Buffer | undefined>(undefined);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    fetch(TEMPLATES).then(response => {
      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }

      response.arrayBuffer().then(async (arrayBuffer) => {
        const buffer = new Uint8Array(arrayBuffer)

        templates = await AutoR1.AutoR1TemplateFile.build(Buffer.from(buffer))
      });
    })
  }, []);

  useEffect(() => {
    if (projectFile) {
      const rows = projectFile.sourceGroups.map(sg => ({ fallback: sg.fallback, mute: sg.mute, ds: sg.dsData }));
      setSourceGroupsStatus(rows);
    }
  }, [projectFile]);

  const handleDragOver = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setIsDragOver(true);
  }

  const handleDragLeave = () => setIsDragOver(false);

  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setIsDragOver(false);
    const droppedFile = event.dataTransfer ? event.dataTransfer.files[0] : (event.target as any).files[0];

    (document.getElementById('fileInput')! as HTMLInputElement).files = event.dataTransfer ? event.dataTransfer.files : (event.target as any).files;

    const reader = new FileReader();
    reader.onload = async (event) => {
      const fileContent = event.target!.result! as ArrayBuffer;
      const buffer = new Uint8Array(fileContent);

      let projectFile: AutoR1.AutoR1ProjectFile;
      try {
        projectFile = await AutoR1.AutoR1ProjectFile.build(Buffer.from(buffer));
        if (projectFile.additions) {
          const id = projectFile.getGroupIdFromName(GROUP_NAME);
          projectFile.clean(id);
        }
        const parentId = projectFile.createGroup({ Name: GROUP_NAME });
        projectFile.createSubLRCGroups(parentId);
        projectFile.getSrcGrpInfo();

        setFileBuffer(Buffer.from(buffer));
        setFileName(droppedFile.name);
        setProjectFile(projectFile);
      } catch (e: any) {
        if (e.message === 'Project file has not been initialised.') {
          alert(`Cannot process ${droppedFile.name}. Project file has not been initialised. Open the project in R1, run the initial setup and save before using AutoR1.`)
        } else {
          alert(`AutoR1 has encountered an error while processing ${droppedFile.name}.`)
        }

        clearFile();
        return;
      }
    };

    reader.readAsArrayBuffer(droppedFile);
  }

  const toggleVisibility = () => {
    setIsVisible(!isVisible);
  };

  const resetStatus = () => {
    const rows = projectFile!.sourceGroups.map(sg => ({ fallback: sg.fallback, mute: sg.mute, ds: sg.dsData }));
    setSourceGroupsStatus(rows);
    setProjectOptions(DEFAULT_OPTIONS);
  }

  const cleanFile = () => {
    if (projectFile) {
      const id = projectFile.getGroupIdFromName(GROUP_NAME);
      projectFile.clean(id);

      return projectFile;
    }
  }

  const clearFile = () => {
    setProjectFile(null);
    setFileName(undefined);
    setSourceGroupsStatus(undefined);
    setFileBuffer(undefined);

    // Clear fileInput
    const fileInput = document.getElementById('fileInput')! as HTMLInputElement;
    fileInput.value = '';
  }

  const statusHasChanged = () => sourceGroupsStatus?.find((row, i) => !row.fallback || !row.mute || !row.ds) || projectOptions.main || projectOptions.meter || projectOptions.eq || projectOptions.arraySightControls;

  return (
    <div id="app">
      <div id="process-container">
        <h1>AutoR1 2.0 Beta</h1>
        <input type="file" id="fileInput" style={projectFile ? { display: 'none' } : { display: 'initial' }} onChange={handleDrop as any} />
      </div>

      <>
        {!projectFile && (
          <div
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              height: "80%",
              width: "80%",
              border: isDragOver ? '2px dashed blue' : '2px solid black'
            }}
          >
            Drag + drop file here
          </div>)}

        {projectFile && sourceGroupsStatus && (
          <div id="projectInfo">
            <div>
              <p>File name: {fileName}</p>
              <p>Initial setup performed: ✅</p>
              <p>Contains AutoR1 additions: {projectFile.additions ? '✅' : '❌'}</p>
            </div>
            <div id="mainButtons">
              <button onClick={async () => {
                const projectFile = await processFile(fileBuffer!, sourceGroupsStatus, projectOptions);

                downloadFile(projectFile, newAutoPath(fileName!));

                alert('Processed project has been downloaded.');
              }}>Run ▶️</button>
              {projectFile.additions && (<button onClick={() => {
                cleanFile();
                downloadFile(projectFile!, fileName!);
              }}>Clean 🧹</button>)
              }
              <button onClick={() => {
                clearFile()
              }}>Clear ⏮️</button>
            </div>
            <div id="statusButtons">
              <button onClick={toggleVisibility}>
                {isVisible ? 'Hide Options ⤴️' : 'Show Options ⤵️'}
              </button>
              {isVisible && statusHasChanged() && (<button onClick={resetStatus}>Reset Options ⏪</button>)}
            </div>
            <div>
              {isVisible && (
                <div>
                  <div>
                    <div>
                      <div className='option'>
                        <div>
                          Create Main page
                        </div>
                        <div>
                          <input type='checkbox' checked={projectOptions.main} onChange={() => {
                            setProjectOptions((oldStatus) => ({
                              ...oldStatus,
                              ...{ main: !oldStatus.main }
                            }))
                          }} />
                        </div>
                      </div>
                      <div className='option'>
                        <div>
                          Create Meter page
                        </div>
                        <div>
                          <input type='checkbox' checked={projectOptions.meter} onChange={() => {
                            setProjectOptions((oldStatus) => ({
                              ...oldStatus,
                              ...{ meter: !oldStatus.meter }
                            }))
                          }} />
                        </div>
                      </div>
                      <div className='option'>
                        <div>
                          Create EQ page
                        </div>
                        <div>
                          <input type='checkbox' checked={projectOptions.eq} onChange={() => {
                            setProjectOptions((oldStatus) => ({
                              ...oldStatus,
                              ...{ eq: !oldStatus.eq }
                            }))
                          }} />
                        </div>
                      </div>
                      <div className='option'>
                        <div>
                          Create ArraySight controls
                        </div>
                        <div>
                          <input type='checkbox' checked={projectOptions.arraySightControls} onChange={() => {
                            setProjectOptions((oldStatus) => ({
                              ...oldStatus,
                              ...{ arraySightControls: !oldStatus.arraySightControls }
                            }))
                          }} />
                        </div>
                      </div>
                    </div>
                  </div>
                  <table id="sourceGroupTable">
                    <thead>
                      <tr>
                        <th>Source Group</th>
                        <th onClick={() => {
                          const newStatus = [...sourceGroupsStatus];
                          newStatus.forEach(row => row.fallback = !row.fallback);
                          setSourceGroupsStatus(newStatus);
                        }}>Fallback</th>
                        <th onClick={() => {
                          const newStatus = [...sourceGroupsStatus];
                          newStatus.forEach(row => row.mute = !row.mute);
                          setSourceGroupsStatus(newStatus);
                        }}>Mute</th>
                        <th onClick={() => {
                          const newStatus = [...sourceGroupsStatus];
                          newStatus.forEach(row => row.ds = !row.ds);
                          setSourceGroupsStatus(newStatus);
                        }}>DS Data</th>
                      </tr>
                    </thead>
                    <tbody>

                      {
                        sourceGroupsStatus.map((row, i) => {
                          return (
                            <>
                              <tr>
                                <td onClick={() => {
                                  const newStatus = [...sourceGroupsStatus];
                                  newStatus[i].fallback = !newStatus[i].fallback;
                                  newStatus[i].mute = !newStatus[i].mute;
                                  newStatus[i].ds = !newStatus[i].ds;
                                  setSourceGroupsStatus(newStatus);
                                }}>{projectFile.sourceGroups[i].Name}</td>
                                <td><input type='checkbox' checked={row.fallback} onChange={() => {
                                  const newStatus = [...sourceGroupsStatus];
                                  newStatus[i].fallback = !newStatus[i].fallback;
                                  setSourceGroupsStatus(newStatus);
                                }} /></td>
                                <td><input type='checkbox' checked={row.mute} onChange={() => {
                                  const newStatus = [...sourceGroupsStatus];
                                  newStatus[i].mute = !newStatus[i].mute;
                                  setSourceGroupsStatus(newStatus);
                                }} /></td>
                                <td><input type='checkbox' checked={row.ds} onChange={() => {
                                  const newStatus = [...sourceGroupsStatus];
                                  newStatus[i].ds = !newStatus[i].ds;
                                  setSourceGroupsStatus(newStatus);
                                }} /></td>
                              </tr>
                            </>
                          )
                        })
                      }
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        )}
      </>

      <div id="footer">
        All files are processed on your device. No files are uploaded. An internet connection is not required once the page has loaded.
      </div>
      <div id="donations">
        <a href="https://www.buymeacoffee.com/Lachlanc"><img alt="donation link" src="https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=☕&slug=Lachlanc&button_colour=FFDD00&font_colour=000000&font_family=Inter&outline_colour=000000&coffee_colour=ffffff" /></a>
        <form action="https://www.paypal.com/donate" method="post" target="_top">
          <input type="hidden" name="hosted_button_id" value="RA2QUPH7AFK5J" />
          <input type="image" src="https://www.paypalobjects.com/en_AU/i/btn/btn_donate_SM.gif" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
          <img alt="" src="https://www.paypal.com/en_AU/i/scr/pixel.gif" width="1" height="1" />
        </form>

      </div>
    </div >
  );
}

export default App;
